import { PrismaClient, ToolCategory, PricingType } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting database seed...');

  // Seed AI Tools
  const tools = [
    {
      slug: 'chatgpt',
      name: 'ChatGPT',
      tagline: 'Advanced conversational AI by OpenAI',
      description: 'ChatGPT is a state-of-the-art language model that can help with writing, coding, analysis, and creative tasks. Perfect for developers and traders looking for AI assistance.',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg',
      websiteUrl: 'https://chat.openai.com',
      affiliateLink: 'https://chat.openai.com',
      category: ToolCategory.WRITING,
      tags: ['AI', 'chatbot', 'writing', 'coding'],
      pricing: PricingType.FREEMIUM,
      priceInr: 1650,
      priceUsd: 20,
      freeTier: true,
      features: ['GPT-4 access', 'Code interpreter', 'Web browsing', 'Custom instructions'],
      useCases: ['Code generation', 'Market analysis', 'Content writing', 'Learning'],
      featured: true,
      verified: true,
    },
    {
      slug: 'cursor-ai',
      name: 'Cursor AI',
      tagline: 'AI-first code editor',
      description: 'Cursor is an AI-powered code editor built for productivity. It understands your codebase and helps you write code faster with intelligent suggestions.',
      logoUrl: 'https://cursor.sh/brand/icon.svg',
      websiteUrl: 'https://cursor.sh',
      category: ToolCategory.CODE_GENERATION,
      tags: ['IDE', 'coding', 'AI', 'productivity'],
      pricing: PricingType.FREEMIUM,
      priceInr: 1650,
      priceUsd: 20,
      freeTier: true,
      features: ['AI code completion', 'Chat with codebase', 'Multi-file editing', 'Git integration'],
      useCases: ['Full-stack development', 'Debugging', 'Code refactoring'],
      featured: true,
      verified: true,
    },
    {
      slug: 'midjourney',
      name: 'Midjourney',
      tagline: 'AI art generation tool',
      description: 'Create stunning images from text descriptions. Perfect for designers, marketers, and content creators.',
      logoUrl: 'https://styles.redditmedia.com/t5_5cqy8/styles/communityIcon_5j3v6k9pkva91.png',
      websiteUrl: 'https://midjourney.com',
      category: ToolCategory.IMAGE_VIDEO,
      tags: ['image generation', 'AI art', 'design'],
      pricing: PricingType.SUBSCRIPTION,
      priceInr: 830,
      priceUsd: 10,
      freeTier: false,
      features: ['High-resolution images', 'Style customization', 'Commercial license', 'Fast generation'],
      useCases: ['Marketing materials', 'Social media content', 'Presentations'],
      featured: true,
      verified: true,
    },
    {
      slug: 'notion-ai',
      name: 'Notion AI',
      tagline: 'AI-powered workspace',
      description: 'Notion AI helps you write, brainstorm, edit, and summarize right inside Notion. Perfect for organizing trading strategies and development notes.',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png',
      websiteUrl: 'https://notion.so/product/ai',
      category: ToolCategory.PRODUCTIVITY,
      tags: ['productivity', 'notes', 'AI', 'collaboration'],
      pricing: PricingType.FREEMIUM,
      priceInr: 830,
      priceUsd: 10,
      freeTier: true,
      features: ['AI writing assistant', 'Auto-summarization', 'Translation', 'Templates'],
      useCases: ['Project management', 'Documentation', 'Knowledge base'],
      featured: true,
      verified: true,
    },
    {
      slug: 'github-copilot',
      name: 'GitHub Copilot',
      tagline: 'Your AI pair programmer',
      description: 'GitHub Copilot suggests code and entire functions in real-time. Essential for developers building trading bots and applications.',
      logoUrl: 'https://github.githubassets.com/images/modules/site/copilot/copilot.png',
      websiteUrl: 'https://github.com/features/copilot',
      category: ToolCategory.CODE_GENERATION,
      tags: ['coding', 'AI', 'GitHub', 'IDE'],
      pricing: PricingType.SUBSCRIPTION,
      priceInr: 830,
      priceUsd: 10,
      freeTier: false,
      features: ['Code suggestions', 'Multi-language support', 'Context-aware', 'IDE integration'],
      useCases: ['Web development', 'API integration', 'Algorithm implementation'],
      featured: true,
      verified: true,
    },
    {
      slug: 'perplexity-ai',
      name: 'Perplexity AI',
      tagline: 'AI-powered answer engine',
      description: 'Get instant, accurate answers with cited sources. Perfect for market research and technical learning.',
      logoUrl: 'https://www.perplexity.ai/favicon.svg',
      websiteUrl: 'https://perplexity.ai',
      category: ToolCategory.RESEARCH,
      tags: ['search', 'research', 'AI', 'learning'],
      pricing: PricingType.FREEMIUM,
      priceInr: 1650,
      priceUsd: 20,
      freeTier: true,
      features: ['Source citations', 'Follow-up questions', 'PDF analysis', 'API access'],
      useCases: ['Market research', 'Technical learning', 'Fact-checking'],
      featured: true,
      verified: true,
    },
    {
      slug: 'claude-ai',
      name: 'Claude',
      tagline: 'Anthropic\'s AI assistant',
      description: 'Claude excels at analysis, coding, and long-form content. Great for complex trading strategy analysis and code reviews.',
      logoUrl: 'https://www.anthropic.com/images/icons/claude-avatar.svg',
      websiteUrl: 'https://claude.ai',
      category: ToolCategory.WRITING,
      tags: ['AI', 'chatbot', 'analysis', 'coding'],
      pricing: PricingType.FREEMIUM,
      priceInr: 1650,
      priceUsd: 20,
      freeTier: true,
      features: ['100K context window', 'Code analysis', 'Document analysis', 'Safe & helpful'],
      useCases: ['Code review', 'Data analysis', 'Strategy planning'],
      featured: true,
      verified: true,
    },
    {
      slug: 'copy-ai',
      name: 'Copy.ai',
      tagline: 'AI content generator',
      description: 'Generate marketing copy, blog posts, and social media content in seconds. Essential for indie developers and traders building personal brands.',
      logoUrl: 'https://www.copy.ai/favicon-32x32.png',
      websiteUrl: 'https://copy.ai',
      category: ToolCategory.WRITING,
      tags: ['marketing', 'content', 'copywriting'],
      pricing: PricingType.FREEMIUM,
      priceInr: 3000,
      priceUsd: 36,
      freeTier: true,
      features: ['90+ templates', 'Multi-language', 'Brand voice', 'Team collaboration'],
      useCases: ['Blog writing', 'Email campaigns', 'Social media'],
      featured: false,
      verified: true,
    },
    {
      slug: 'jasper-ai',
      name: 'Jasper AI',
      tagline: 'Enterprise AI content platform',
      description: 'Jasper helps teams create content faster with AI. Ideal for trading education content and developer tutorials.',
      logoUrl: 'https://www.jasper.ai/favicon.ico',
      websiteUrl: 'https://jasper.ai',
      category: ToolCategory.WRITING,
      tags: ['marketing', 'content', 'enterprise'],
      pricing: PricingType.SUBSCRIPTION,
      priceInr: 3250,
      priceUsd: 39,
      freeTier: false,
      features: ['Brand voice', 'SEO optimization', 'Team collaboration', 'Templates'],
      useCases: ['Marketing content', 'Educational content', 'Sales copy'],
      featured: false,
      verified: true,
    },
    {
      slug: 'descript',
      name: 'Descript',
      tagline: 'AI-powered video editing',
      description: 'Edit videos as easily as editing text. Perfect for creating trading tutorials and developer screencasts.',
      logoUrl: 'https://www.descript.com/favicon.ico',
      websiteUrl: 'https://descript.com',
      category: ToolCategory.IMAGE_VIDEO,
      tags: ['video editing', 'podcasting', 'AI'],
      pricing: PricingType.FREEMIUM,
      priceInr: 1000,
      priceUsd: 12,
      freeTier: true,
      features: ['Transcription', 'AI voices', 'Screen recording', 'Collaboration'],
      useCases: ['Tutorial creation', 'Podcast editing', 'Marketing videos'],
      featured: false,
      verified: true,
    },
    {
      slug: 'make-com',
      name: 'Make (Integromat)',
      tagline: 'Visual automation platform',
      description: 'Automate workflows between apps without code. Essential for automating trading alerts and development workflows.',
      logoUrl: 'https://www.make.com/favicon.ico',
      websiteUrl: 'https://make.com',
      category: ToolCategory.AUTOMATION,
      tags: ['automation', 'integration', 'no-code'],
      pricing: PricingType.FREEMIUM,
      priceInr: 750,
      priceUsd: 9,
      freeTier: true,
      features: ['Visual builder', '1000+ integrations', 'Advanced logic', 'Error handling'],
      useCases: ['Trading alerts', 'Data pipelines', 'Workflow automation'],
      featured: false,
      verified: true,
    },
    {
      slug: 'zapier',
      name: 'Zapier',
      tagline: 'Automate your work',
      description: 'Connect your apps and automate workflows. Great for automating repetitive tasks in trading and development.',
      logoUrl: 'https://cdn.zapier.com/zapier/images/favicon.ico',
      websiteUrl: 'https://zapier.com',
      category: ToolCategory.AUTOMATION,
      tags: ['automation', 'integration', 'productivity'],
      pricing: PricingType.FREEMIUM,
      priceInr: 1650,
      priceUsd: 20,
      freeTier: true,
      features: ['5000+ integrations', 'Multi-step zaps', 'AI-powered', 'Team collaboration'],
      useCases: ['Data sync', 'Notifications', 'Report generation'],
      featured: false,
      verified: true,
    },
    {
      slug: 'tableau',
      name: 'Tableau',
      tagline: 'Data visualization platform',
      description: 'Turn data into actionable insights with stunning visualizations. Essential for analyzing trading data and metrics.',
      logoUrl: 'https://www.tableau.com/favicon.ico',
      websiteUrl: 'https://tableau.com',
      category: ToolCategory.DATA_ANALYSIS,
      tags: ['analytics', 'visualization', 'business intelligence'],
      pricing: PricingType.SUBSCRIPTION,
      priceInr: 5800,
      priceUsd: 70,
      freeTier: false,
      features: ['Interactive dashboards', 'Real-time data', 'AI insights', 'Mobile app'],
      useCases: ['Trading analytics', 'Performance dashboards', 'Data exploration'],
      featured: false,
      verified: true,
    },
    {
      slug: 'canva-ai',
      name: 'Canva AI',
      tagline: 'Design with AI magic',
      description: 'Create professional designs with AI assistance. Perfect for social media posts, presentations, and marketing materials.',
      logoUrl: 'https://static.canva.com/web/images/favicon.ico',
      websiteUrl: 'https://canva.com',
      category: ToolCategory.DESIGN,
      tags: ['design', 'graphics', 'AI', 'templates'],
      pricing: PricingType.FREEMIUM,
      priceInr: 1000,
      priceUsd: 12,
      freeTier: true,
      features: ['Magic Design', 'Brand kit', 'Templates', 'Team collaboration'],
      useCases: ['Social media', 'Presentations', 'Marketing materials'],
      featured: false,
      verified: true,
    },
    {
      slug: 'grammarly',
      name: 'Grammarly',
      tagline: 'AI writing assistant',
      description: 'Improve your writing with AI-powered suggestions. Essential for professional communication and content creation.',
      logoUrl: 'https://static.grammarly.com/assets/files/efe9369d9439fa7863e1f0b5264faeaa/favicon.svg',
      websiteUrl: 'https://grammarly.com',
      category: ToolCategory.WRITING,
      tags: ['writing', 'grammar', 'productivity'],
      pricing: PricingType.FREEMIUM,
      priceInr: 1000,
      priceUsd: 12,
      freeTier: true,
      features: ['Grammar check', 'Tone detection', 'Plagiarism', 'Style guide'],
      useCases: ['Professional emails', 'Documentation', 'Content writing'],
      featured: false,
      verified: true,
    },
    {
      slug: 'tradingview',
      name: 'TradingView',
      tagline: 'Charting platform for traders',
      description: 'Advanced charting and social trading platform. Must-have for technical analysis and trading strategies.',
      logoUrl: 'https://static.tradingview.com/static/images/favicon.ico',
      websiteUrl: 'https://tradingview.com',
      category: ToolCategory.TRADING,
      tags: ['trading', 'charts', 'technical analysis'],
      pricing: PricingType.FREEMIUM,
      priceInr: 1250,
      priceUsd: 15,
      freeTier: true,
      features: ['Real-time data', 'Custom indicators', 'Alerts', 'Paper trading'],
      useCases: ['Technical analysis', 'Strategy backtesting', 'Market research'],
      featured: true,
      verified: true,
    },
    {
      slug: 'figma-ai',
      name: 'Figma AI',
      tagline: 'Collaborative design tool with AI',
      description: 'Design, prototype, and collaborate in real-time. Essential for UI/UX designers and developers.',
      logoUrl: 'https://static.figma.com/app/icon/1/favicon.ico',
      websiteUrl: 'https://figma.com',
      category: ToolCategory.DESIGN,
      tags: ['design', 'prototyping', 'collaboration'],
      pricing: PricingType.FREEMIUM,
      priceInr: 1000,
      priceUsd: 12,
      freeTier: true,
      features: ['Real-time collaboration', 'Prototyping', 'Design systems', 'Dev mode'],
      useCases: ['UI design', 'Prototyping', 'Design handoff'],
      featured: false,
      verified: true,
    },
    {
      slug: 'replit-ai',
      name: 'Replit AI',
      tagline: 'AI-powered online IDE',
      description: 'Code, deploy, and host apps in the browser with AI assistance. Perfect for quick prototypes and learning.',
      logoUrl: 'https://replit.com/public/images/favicon.ico',
      websiteUrl: 'https://replit.com',
      category: ToolCategory.CODE_GENERATION,
      tags: ['IDE', 'coding', 'AI', 'deployment'],
      pricing: PricingType.FREEMIUM,
      priceInr: 1650,
      priceUsd: 20,
      freeTier: true,
      features: ['AI code completion', 'Instant deployment', 'Collaboration', 'Multiple languages'],
      useCases: ['Learning', 'Prototyping', 'Quick projects'],
      featured: false,
      verified: true,
    },
    {
      slug: 'synthesia',
      name: 'Synthesia',
      tagline: 'AI video generation',
      description: 'Create AI-generated videos from text. Great for creating trading tutorials and educational content at scale.',
      logoUrl: 'https://www.synthesia.io/favicon.ico',
      websiteUrl: 'https://synthesia.io',
      category: ToolCategory.IMAGE_VIDEO,
      tags: ['video', 'AI', 'avatars'],
      pricing: PricingType.SUBSCRIPTION,
      priceInr: 2500,
      priceUsd: 30,
      freeTier: false,
      features: ['AI avatars', '120+ languages', 'Custom avatars', 'Screen recording'],
      useCases: ['Tutorial videos', 'Training content', 'Marketing videos'],
      featured: false,
      verified: true,
    },
    {
      slug: 'postman',
      name: 'Postman',
      tagline: 'API development platform',
      description: 'Build, test, and collaborate on APIs. Essential for developers integrating trading APIs and building applications.',
      logoUrl: 'https://www.postman.com/favicon-32x32.png',
      websiteUrl: 'https://postman.com',
      category: ToolCategory.CODE_GENERATION,
      tags: ['API', 'development', 'testing'],
      pricing: PricingType.FREEMIUM,
      priceInr: 1250,
      priceUsd: 15,
      freeTier: true,
      features: ['API testing', 'Mock servers', 'Documentation', 'Team collaboration'],
      useCases: ['API integration', 'Testing', 'Documentation'],
      featured: false,
      verified: true,
    },
  ];

  console.log('📝 Creating tools...');
  
  for (const tool of tools) {
    await prisma.tool.upsert({
      where: { slug: tool.slug },
      update: tool,
      create: tool,
    });
    console.log(`✅ Created/Updated: ${tool.name}`);
  }

  console.log('\n🎉 Seed completed successfully!');
  console.log(`📊 Total tools created: ${tools.length}`);
  console.log(`⭐ Featured tools: ${tools.filter(t => t.featured).length}`);
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
